// <auto-generated />
namespace CartoSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FlowType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FlowType));
        
        string IMigrationMetadata.Id
        {
            get { return "201309161224459_FlowType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
