// <auto-generated />
namespace CartoSys.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FlowTypeNumeric : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FlowTypeNumeric));
        
        string IMigrationMetadata.Id
        {
            get { return "201309191506595_FlowTypeNumeric"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
